### PR TITLE
iterate over last dimension when grouping N-D tables of images

### LINKED ISSUE #625: Incorrect grouping in multidimensional table of images
I love the table display introduced in https://github.com/JuliaImages/Images.jl/pull/574 :smile: 

But I think it might be grouping arrays of images with more than 2 dimensions in an odd way. Specifically, if I do the following:

```julia
using Colors
[fill(Gray{Float32}(z), 2, 2) for x in 1:2, y in 1:2, z in 0:1]
```

(the `fill(..., 2, 2)` is necessary to work around #623 )

I see:

```
2×2×2 Array{Array{ColorTypes.Gray{Float32},2},3}:
[:, :, 1] =
 ColorTypes.Gray{Float32}[Gray{Float32}(0.0) Gray{Float32}(0.0); Gray{Float32}(0.0) Gray{Float32}(0.0)]  …  ColorTypes.Gray{Float32}[Gray{Float32}(0.0) Gray{Float32}(0.0); Gray{Float32}(0.0) Gray{Float32}(0.0)]
 ColorTypes.Gray{Float32}[Gray{Float32}(0.0) Gray{Float32}(0.0); Gray{Float32}(0.0) Gray{Float32}(0.0)]     ColorTypes.Gray{Float32}[Gray{Float32}(0.0) Gray{Float32}(0.0); Gray{Float32}(0.0) Gray{Float32}(0.0)]

[:, :, 2] =
 ColorTypes.Gray{Float32}[Gray{Float32}(1.0) Gray{Float32}(1.0); Gray{Float32}(1.0) Gray{Float32}(1.0)]  …  ColorTypes.Gray{Float32}[Gray{Float32}(1.0) Gray{Float32}(1.0); Gray{Float32}(1.0) Gray{Float32}(1.0)]
 ColorTypes.Gray{Float32}[Gray{Float32}(1.0) Gray{Float32}(1.0); Gray{Float32}(1.0) Gray{Float32}(1.0)]     ColorTypes.Gray{Float32}[Gray{Float32}(1.0) Gray{Float32}(1.0); Gray{Float32}(1.0) Gray{Float32}(1.0)]
```

The above is hard to read, but the important point is that Julia arrays display in chunks by `[:, :, 1]`, `[:, :, 2]`, etc... which you can confirm by observing that the Gray values in the second chunk are all 1. 

When I load the Images.jl display code, however, I see:

screenshot from 2017-04-13 16 16 08

which groups the elements differently. 

I think the fix for this is just to switch `i` and `colons...` in https://github.com/JuliaImages/Images.jl/blob/master/src/showmime.jl#L65 and https://github.com/JuliaImages/Images.jl/blob/master/src/showmime.jl#L53 but I'd like to make sure this isn't the intended behavior before I try to change that.

### PR DESCRIPTION
**Pull request by rdeits**
Fixes #625 (assuming that that is, in fact, an error). 

Before:

screenshot from 2017-04-13 16 58 35

After:

screenshot from 2017-04-13 16 57 38

My reasoning is that this is more consistent with the way arrays are printed as text in Julia:

```julia
[fill(z * z2) for x in 1:2, y in 1:2, z in [0.5, 1], z2 in [0.5, 1]]
```

gives:

```
2×2×2×2 Array{Array{Float64,0},4}:
[:, :, 1, 1] =
 0.25  0.25
 0.25  0.25

[:, :, 2, 1] =
 0.5  0.5
 0.5  0.5

[:, :, 1, 2] =
 0.5  0.5
 0.5  0.5

[:, :, 2, 2] =
 1.0  1.0
 1.0  1.0
```

### CODE REVIEW

**Comment by rdeits** [comment]
Derp, this doesn't handle dimensions with length > 2 correctly. Please don't merge yet.

**Comment by rdeits** [comment]
Ok, fixed.

File: src/showmime.jl [hunk 1]
```diff
@@ -48,9 +48,9 @@ end
 
 function _show_odd{T<:ColorantArray, N}(io::IO, m::MIME"text/html", imgs::AbstractArray{T, N})
```
Comment (timholy) [inline src/showmime.jl]: Presumably this needs to be updated to `ColorantMatrix` now? (Sorry if I merged the PRs in the wrong order!)

Comment (rdeits) [inline src/showmime.jl]: No problem. I've rebased this branch, so it should be fixed now.

**Comment by rdeits** [comment]
Actually, there's one more issue to resolve: this change results in the table of images being displayed in a row-major ordering, which is inconsistent with the rest of Julia. Let me see if I can fix that...

File: src/showmime.jl [hunk 2]
```diff
@@ -48,9 +48,9 @@ end
 
 function _show_odd{T<:ColorantMatrix, N}(io::IO, m::MIME"text/html", imgs::AbstractArray{T, N})
     colons = ([Colon() for i=1:(N-1)]...)
-    for i = 1:size(imgs, 1)
+    for i = 1:size(imgs, N)
```
Comment (Evizero) [inline src/showmime.jl]: is it worth changing this to `for i in indices(imgs, N)` ?

**Comment by rdeits** [comment]
Oh, never mind; that's clearly the intended behavior, since a vector of images is displayed as a row.

File: src/showmime.jl (hunk 2 above)
Comment (rdeits) [inline src/showmime.jl]: Good point. I'll do that.

Comment (rdeits) [inline src/showmime.jl]: ok, done

**Comment by timholy** [comment]
Thanks!
