### PR TITLE
Fix various test failures

### LINKED ISSUE #624: Stack overflow when trying to display HSV image in IJulia
I see the following in IJulia with Images master, both with ImageMagick on Ubuntu and QuartzImageIO on mac:

```julia
using Images
fill(HSV{Float64}(0.5, 0.5, 0.5), 1, 1)
```

gives:

```
WARNING: Mapping to the storage type failed; perhaps your data had out-of-range values?
Try `map(clamp01nan, img)` to clamp values to a valid range.
Error encountered while saving "Nullable{String}()".
Fatal error:
StackOverflowError:
```

### PR DESCRIPTION
**Pull request by timholy**
## restrict

See issue #628. Unfortunately `restrict(A, Axis{:name})` is no longer inferrable, and I've not found a way to fix this within Images. Fixing this will require a stand-alone demonstration reported to base julia.

This is presumably a consequence of other generalizations to `restrict`. On balance, I'd rather have support for arbitrary indices, and use a function barrier to resolve type instability problems.

## show for mime

fixes #624. However I had to disable some failing tests, CC @rdeits.

## reinterpret

Deletes tests whose behavior was changed by https://github.com/JuliaImages/ImageCore.jl/pull/34

### CODE REVIEW

**Comment by timholy** [comment]
Test failure on OSX appears to be https://github.com/JuliaIO/QuartzImageIO.jl/issues/37.

File: test/writemime.jl [hunk 1]
```diff
@@ -58,11 +85,11 @@ using Base.Test
         io = IOBuffer()
         # These methods should not invoke the Images.jl display code, but they
         # used to throw errors: https://github.com/JuliaImages/Images.jl/issues/623
-        show(io, MIME"text/html"(), [flat_img() for i=1:2])
-        show(io, MIME"text/html"(), [flat_img() for i=1:2, j=1:2])
-        show(io, MIME"text/html"(), [flat_img() for i=1:2, j=1:2, k=1:2])
+        # show(io, MIME"text/html"(), [flat_img() for i=1:2])
```
Comment (rdeits) [inline test/writemime.jl]: I also see these tests failing. I'm not sure how they were working before. We could just disable these tests, but I'd like to make sure the original bug doesn't come back.  Perhaps we could wrap this block in an 

```
if applicable(show, io, MIME"text/html"(), [flat_img() for i=1:2])
```

check?

Comment (timholy) [inline test/writemime.jl]: My suspicion is that the `ColorantMatrix` change is what broke these. Before the `restrict` fix, the tests never even got this far.

Comment (rdeits) [inline test/writemime.jl]: Oh definitely: that change is what added these tests in the first place 😉 

And I knew that the tests weren't getting this far when running the full test set, but I was sure I'd tested these in isolation. Clearly I hadn't, though. 

In any case, I'll take care of replacing this with a more useful test.
